package com.haniokasai.app.pmmp_srv;

import android.content.Context;
import android.util.Log;

import org.apache.commons.compress.archivers.tar.TarArchiveEntry;
import org.apache.commons.compress.archivers.tar.TarArchiveInputStream;
import org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream;

import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

/**
 * Manages the frp client (frpc) for tunneling the MCPE server to a public frp
 * server the user controls.
 *
 * frpc is a static Go binary (no libc), so the linux_arm64 build runs on
 * Android the same way the bundled arm64 PHP does. We download it at runtime
 * (like PHP) instead of bloating the APK, then launch it as a child process
 * alongside the server and stream its log to the console under the [frp] tag.
 */
public final class FrpManager {

    public static final String TAG = "FrpManager";
    /** Default frp release; overridable in the UI for newer/older builds. */
    public static final String DEFAULT_VERSION = "0.71.0";

    private static Process frpProcess;
    private static OutputStream frpStdin;

    private FrpManager() {
    }

    public static String getFrpcPath(Context c) {
        return c.getApplicationInfo().dataDir + "/frpc";
    }

    public static boolean isFrpcInstalled(Context c) {
        return new File(getFrpcPath(c)).exists();
    }

    /** Builds the GitHub release URL for the linux_arm64 frpc tarball. */
    public static String defaultUrl(String version) {
        return "https://github.com/fatedier/frp/releases/download/v" + version
                + "/frp_" + version + "_linux_arm64.tar.gz";
    }

    public interface FrpInstallListener {
        void onProgress(String message);

        void onSuccess(String versionInfo);

        void onFailure(String error);
    }

    /** Downloads the frpc tarball and installs the frpc binary. */
    public static void installFromUrl(Context context, String url, FrpInstallListener listener) {
        File appDir = new File(context.getApplicationInfo().dataDir);
        File cache = new File(appDir, "frpc_download.tar.gz");
        try {
            listener.onProgress(context.getString(R.string.frp_downloading, url));
            downloadFile(url, cache);
            File extractDir = new File(appDir, "frpc_extract");
            deleteRecursively(extractDir);
            extractDir.mkdirs();

            listener.onProgress(context.getString(R.string.frp_extracting));
            extractTarGz(cache, extractDir);

            File frpcBin = findFile(extractDir, "frpc");
            if (frpcBin == null) {
                throw new Exception("frpc binary not found in archive");
            }
            File dest = new File(getFrpcPath(context));
            copyFile(frpcBin, dest);
            if (!PhpManager.makeExecutable(dest)) {
                throw new Exception("Cannot make frpc executable (permission denied)");
            }
            cache.delete();
            deleteRecursively(extractDir);

            String ver = getFrpcVersion(dest);
            listener.onSuccess(ver != null ? ver : "frpc");
        } catch (Exception e) {
            listener.onFailure(e.getMessage());
        }
    }

    /**
     * Writes the frpc.toml from the current AppSettings into the app data dir
     * and returns the file. MCPE speaks UDP on its port, so the proxy type is
     * "udp".
     */
    public static File writeConfig(Context c) throws Exception {
        File cfg = new File(c.getApplicationInfo().dataDir, "frpc.toml");
        String addr = AppSettings.frpServerAddr(c).trim();
        int serverPort = AppSettings.frpServerPort(c);
        String token = AppSettings.frpToken(c);
        int localPort = AppSettings.frpLocalPort(c);
        int remotePort = AppSettings.frpRemotePort(c);

        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by XuanFeng. Edit and restart the server to apply.\n");
        sb.append("serverAddr = \"").append(addr).append("\"\n");
        sb.append("serverPort = ").append(serverPort).append("\n");
        sb.append("\n");
        sb.append("[auth]\n");
        sb.append("method = \"token\"\n");
        sb.append("token = \"").append(token).append("\"\n");
        sb.append("\n");
        sb.append("[[proxies]]\n");
        sb.append("name = \"minecraft-pe\"\n");
        sb.append("type = \"udp\"\n");
        sb.append("localIP = \"127.0.0.1\"\n");
        sb.append("localPort = ").append(localPort).append("\n");
        sb.append("remotePort = ").append(remotePort).append("\n");

        try (FileOutputStream os = new FileOutputStream(cfg)) {
            os.write(sb.toString().getBytes(StandardCharsets.UTF_8));
        }
        return cfg;
    }

    public static void start(Context c) {
        if (frpProcess != null && isAlive(frpProcess)) {
            ConsoleActivity.log("[frp] Already running; not starting a second instance.");
            return;
        }
        try {
            File cfg = writeConfig(c);
            List<String> args = new ArrayList<>();
            args.add(getFrpcPath(c));
            args.add("-c");
            args.add(cfg.getAbsolutePath());
            ProcessBuilder pb = new ProcessBuilder(args);
            pb.redirectErrorStream(true);
            try {
                frpProcess = pb.start();
            } catch (Exception e) {
                ConsoleActivity.log("[frp] Failed to start frpc: " + e.getMessage());
                return;
            }
            frpStdin = frpProcess.getOutputStream();
            ConsoleActivity.log("[frp] frpc started (config: " + cfg.getAbsolutePath() + ")");
            Thread t = new Thread(FrpManager::monitor);
            t.setName("frp-monitor");
            t.start();
        } catch (Exception e) {
            ConsoleActivity.log("[frp] Could not start frpc: " + e.getMessage());
        }
    }

    public static void stop() {
        if (frpProcess == null) return;
        ConsoleActivity.log("[frp] Stopping frpc…");
        try {
            if (frpStdin != null) {
                frpStdin.write("quit\n".getBytes(StandardCharsets.UTF_8));
                frpStdin.flush();
            }
        } catch (Exception ignored) {
        }
        try {
            frpProcess.destroyForcibly();
        } catch (Exception ignored) {
        }
        frpProcess = null;
        frpStdin = null;
    }

    public static boolean isRunning() {
        if (frpProcess == null) return false;
        try {
            frpProcess.exitValue();
            return false;
        } catch (IllegalThreadStateException e) {
            return true;
        }
    }

    private static void monitor() {
        if (frpProcess == null) return;
        try {
            InputStream in = frpProcess.getInputStream();
            BufferedReader br = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8));
            String line;
            while ((line = br.readLine()) != null) {
                ConsoleActivity.log("[frp] " + line);
            }
        } catch (Exception ignored) {
        } finally {
            ConsoleActivity.log("[frp] frpc process exited.");
        }
    }

    private static boolean isAlive(Process p) {
        try {
            p.exitValue();
            return false;
        } catch (IllegalThreadStateException e) {
            return true;
        }
    }

    private static String getFrpcVersion(File frpc) {
        try {
            Process p = Runtime.getRuntime().exec(new String[]{frpc.getAbsolutePath(), "--version"});
            BufferedReader br = new BufferedReader(
                    new InputStreamReader(p.getInputStream(), StandardCharsets.UTF_8));
            String line = br.readLine();
            br.close();
            p.waitFor();
            return line != null && !line.isEmpty() ? line.trim() : null;
        } catch (Exception e) {
            return null;
        }
    }

    // ------------------------------------------------------------------
    // Internal helpers (tar extraction + download, mirror of PhpManager).
    // ------------------------------------------------------------------

    private static void downloadFile(String url, File saveTo) throws Exception {
        if (saveTo.exists()) saveTo.delete();
        URL u = new URL(url);
        try (InputStream input = new BufferedInputStream(u.openStream());
             OutputStream output = new FileOutputStream(saveTo)) {
            byte[] buffer = new byte[8192];
            int count;
            while ((count = input.read(buffer)) >= 0) {
                output.write(buffer, 0, count);
            }
        }
    }

    private static void extractTarGz(File archive, File destDir) throws Exception {
        try (InputStream fi = new java.io.FileInputStream(archive);
             BufferedInputStream bi = new BufferedInputStream(fi);
             GzipCompressorInputStream gzi = new GzipCompressorInputStream(bi)) {
            extractTarStream(gzi, destDir);
        }
    }

    private static void extractTarStream(InputStream tarStream, File destDir) throws Exception {
        try (TarArchiveInputStream tis = new TarArchiveInputStream(tarStream)) {
            TarArchiveEntry entry;
            while ((entry = tis.getNextTarEntry()) != null) {
                File out = new File(destDir, entry.getName());
                if (entry.isDirectory()) {
                    out.mkdirs();
                    continue;
                }
                File parent = out.getParentFile();
                if (parent != null) parent.mkdirs();
                try (OutputStream os = new FileOutputStream(out)) {
                    byte[] buf = new byte[8192];
                    int n;
                    while ((n = tis.read(buf)) >= 0) {
                        os.write(buf, 0, n);
                    }
                }
                int mode = entry.getMode();
                if ((mode & 0100) != 0) {
                    PhpManager.makeExecutable(out);
                }
            }
        }
    }

    private static File findFile(File root, String name) {
        if (root == null || !root.isDirectory()) return null;
        File[] files = root.listFiles();
        if (files == null) return null;
        for (File f : files) {
            if (f.isDirectory()) {
                File found = findFile(f, name);
                if (found != null) return found;
            } else if (f.getName().equals(name)) {
                return f;
            }
        }
        return null;
    }

    private static void copyFile(File src, File dst) throws Exception {
        try (InputStream in = new java.io.FileInputStream(src);
             OutputStream out = new FileOutputStream(dst)) {
            byte[] buf = new byte[8192];
            int n;
            while ((n = in.read(buf)) >= 0) out.write(buf, 0, n);
        }
    }

    private static void deleteRecursively(File dir) {
        if (dir == null || !dir.exists()) return;
        File[] files = dir.listFiles();
        if (files != null) {
            for (File f : files) {
                if (f.isDirectory()) deleteRecursively(f);
                else f.delete();
            }
        }
        dir.delete();
    }
}
